substitutions:
  name: esphome-web-6c37b0
  friendly_name: Downstairs mini split

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome

logger:
  level: INFO
  logs:
    mitsubishi_cn105: WARN
    climate: WARN
    sensor: WARN

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO21
  rx_pin: GPIO20
  parity: EVEN
  stop_bits: 1

climate:
  - platform: mitsubishi_cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump
    uart_id: HP_UART
    visual:
      min_temperature: 16
      max_temperature: 26
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.5
    update_interval: 4s

sensor:
  - platform: uptime
    name: "Uptime"

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 2
