substitutions:
  name: bedroom_mini_split
  friendly_name: Bedroom Mini Split

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
  variant: esp32c3

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO20
  rx_pin: GPIO21

external_components:
  - source: github://echavet/MitsubishiCN105ESPHome

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

captive_portal:

logger:
  level: INFO

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    icon: mdi:heat-pump

    # Update interval - adjust based on your needs (1-4s recommended)
    update_interval: 2s

    # Debounce delay for commands
    debounce_delay: 100ms

sensor:
  - platform: uptime
    name: "Uptime"
